###  How to solve basic Python Problems and what are the common errors we face

You need to follow the below main points to become a good programmer

   - Break a problem into a smaller sub-problems
   - Trying to find the logic and try to connect them from sub problem
   - After completing sub-problems then putting them all together
   - More Focus of common error and mistakes and always reading function referneces and focus on fixting the bugs
   - Try to do more and more practice.
   - Try to Introduce new concepts as we need.
   - During beginning you have to do more focus of self placed code and try to see other codes but always write self.
   - As you become more and more good in self written program after that you can use others code to save your time.

#### Problem1- Add two randomly generated Numpy matrics using loop

In [1]:
# Create random matrix AI of sixe 5x4
import numpy as np
A1 = np.random.rand(5,4)
print(A1) ## Always try to print theoutput to check what you were thinking that is same or not.

[[3.07663063e-01 8.80558774e-01 3.32803421e-02 7.56220722e-02]
 [8.32056304e-01 7.58552918e-01 5.55077282e-01 7.98087797e-02]
 [9.22900315e-01 8.19686996e-01 8.36227641e-01 6.86522544e-01]
 [8.99110073e-01 8.09299457e-01 2.64715416e-02 3.66959439e-01]
 [1.11467059e-01 3.34172177e-01 2.71474242e-04 1.05321205e-01]]


In [2]:
print(A1.shape)  ### It return a tuple of integers
print(type(A1))

(5, 4)
<class 'numpy.ndarray'>


In [3]:
# common error whilke using type and shape
print(A1.type)
# from the error you can clearly see that array (AI) has no attribute like "type"- 
# Please refer python numpy type doc

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [4]:
# common error whilke using type and shape
print(A1.shape())
# you can see that 'tuple' object is not callable. What we normally call like function of methods
# but what is the output of A1.shape as per document is tuple of integer(5,4) so tuple is not a function thats why 
# we are getting error that 'tuple' object is not callable

TypeError: 'tuple' object is not callable

In [5]:
# Create random matrix A2 of sixe 5x4
A2 = np.random.rand(5,4)
print(A2)
print(type(A2))
print(A2.shape)

[[0.06604307 0.66724437 0.58918478 0.59010481]
 [0.51253517 0.32564438 0.84213962 0.16862697]
 [0.25824264 0.39145179 0.77202171 0.13528329]
 [0.3514634  0.07028182 0.00353917 0.62966624]
 [0.59826791 0.6188575  0.93139574 0.90943783]]
<class 'numpy.ndarray'>
(5, 4)


In [6]:
# While accessing the element of ndarray (e.g. A2)
# lets what is value of i,j th element in the ndarray A2 ===  print(A2[i,j])
print(A2[2,3])

0.13528329097503744


In [7]:
## common error
print(A2(2,3))  ## A2 is a nd array so we can not call () this

TypeError: 'numpy.ndarray' object is not callable

In [8]:
## Add numpy nd array using operator +
B = A1 + A2
print(B)
print(type(B))
print(A2.shape)

[[0.37370613 1.54780314 0.62246512 0.66572688]
 [1.34459147 1.0841973  1.3972169  0.24843575]
 [1.18114295 1.21113879 1.60824935 0.82180583]
 [1.25057348 0.87958127 0.03001071 0.99662568]
 [0.70973497 0.95302967 0.93166722 1.01475904]]
<class 'numpy.ndarray'>
(5, 4)


In [9]:
# A1.shape  == output is a tuple of interger like (5,4)
(r,c) = A1.shape
(r,c)

(5, 4)

In [10]:
for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j]
print(B)

[[0.37370613 1.54780314 0.62246512 0.66572688]
 [1.34459147 1.0841973  1.3972169  0.24843575]
 [1.18114295 1.21113879 1.60824935 0.82180583]
 [1.25057348 0.87958127 0.03001071 0.99662568]
 [0.70973497 0.95302967 0.93166722 1.01475904]]


In [11]:
range(r)

range(0, 5)

In [12]:
range(c)

range(0, 4)

In [13]:
# Optomization : Pre allocated matrix B12
# in the above eg size of the B12 is getting change on each iteration within the loop and if we have very large
# matrix than it will consume lots of memory
#  so better to pre assign B12
# create mAtrix B with all Zeros. Once we assign B12 then it will get alocated ram or memory witnin B12.
B = np.zeros((5,4)) ## Return a new array of given shape and type, filled with zeros.

In [14]:
### Common error while np.zero
np.zeros(5,4) #### it takes shaoe in int or tupe of integers so we can either gice 20, or tuple(5,4)

TypeError: data type not understood

In [15]:
print(B)
print(B.shape)
print(type(B))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(5, 4)
<class 'numpy.ndarray'>


In [16]:
B12 = np.zeros((5,4))
for i in range(r):
    for j in range(c):
        B12[i,j] = A1[i,j] + A2[i,j]
print(B12)

[[0.37370613 1.54780314 0.62246512 0.66572688]
 [1.34459147 1.0841973  1.3972169  0.24843575]
 [1.18114295 1.21113879 1.60824935 0.82180583]
 [1.25057348 0.87958127 0.03001071 0.99662568]
 [0.70973497 0.95302967 0.93166722 1.01475904]]


Time complexity -- for above O(rxc)
https://medium.com/fintechexplained/time-complexities-of-python-data-structures-ddb7503790ef
https://towardsdatascience.com/understanding-time-complexity-with-python-examples-2bda6e8158a7
Space complexity  -- we are not counting input and output variable becuase these will be sue is most of the algorith
and also we are using variable i,j,r,c and these are constant number are variables so space complexity is O(1) it means its is constant
https://www.studytonight.com/data-structures/space-complexity-of-algorithms

#### Problem2- Add two randomly generated Numpy matrics using loop having shape (i,j,k)

In [17]:
C1 = np.random.rand(5,4,3)
print(C1)
print(type(C1))
print(C1.shape)

[[[0.28473478 0.45926118 0.70069167]
  [0.12830522 0.96805773 0.35559431]
  [0.32165373 0.31599596 0.91423717]
  [0.44551682 0.40804737 0.61148373]]

 [[0.88564173 0.80536462 0.67042247]
  [0.33358848 0.95099955 0.47782613]
  [0.79041385 0.48284027 0.6387112 ]
  [0.59819373 0.30063074 0.1260047 ]]

 [[0.88549347 0.9130611  0.17803596]
  [0.43709825 0.43306024 0.2274859 ]
  [0.54722853 0.20093175 0.4482139 ]
  [0.81826578 0.03242577 0.11674702]]

 [[0.72223874 0.79411414 0.65676905]
  [0.39052235 0.5287275  0.03542766]
  [0.1962492  0.29159444 0.37387489]
  [0.59201271 0.20158388 0.95347826]]

 [[0.91031606 0.24041722 0.88309426]
  [0.96138799 0.16947598 0.06610262]
  [0.94015986 0.74408801 0.23208257]
  [0.14049583 0.00700068 0.14132412]]]
<class 'numpy.ndarray'>
(5, 4, 3)


In [18]:
C2 = np.random.rand(5,4,3)
print(C2)
print(type(C2))
print(C2.shape)

[[[0.00697869 0.97305963 0.22988707]
  [0.50729203 0.88534347 0.92345039]
  [0.67273561 0.9189238  0.57844302]
  [0.02566959 0.98033824 0.34592294]]

 [[0.7109668  0.03684416 0.67850825]
  [0.08699613 0.35850867 0.23407748]
  [0.39585668 0.59970612 0.69061715]
  [0.64213058 0.31174716 0.06098371]]

 [[0.34406313 0.77827515 0.31664334]
  [0.37424633 0.15818697 0.55737598]
  [0.59102193 0.31067538 0.64359108]
  [0.85116368 0.64595436 0.4428416 ]]

 [[0.62338523 0.59851113 0.01212844]
  [0.50191213 0.1239009  0.22335628]
  [0.84881228 0.46436619 0.33123731]
  [0.14037891 0.84460144 0.2279739 ]]

 [[0.65137958 0.38536114 0.2212713 ]
  [0.69084649 0.26872849 0.51937193]
  [0.62378281 0.85335249 0.77734037]
  [0.44568422 0.98102524 0.15583209]]]
<class 'numpy.ndarray'>
(5, 4, 3)


In [19]:
# C[i,j,k] = C1[i,j,k]+C2[i,j,k]
C = np.zeros((5,4,3))
(c,r,t)=C.shape

In [20]:
print(c)
print(r)
print(t)

5
4
3


In [21]:
for i in range(c):
    for j in range(r):
        for k in range(t):
            C[i,j,k] = C1[i,j,k]+C2[i,j,k]
print(C)
print(type(C))
print(C.shape)

[[[0.29171348 1.43232081 0.93057874]
  [0.63559725 1.8534012  1.27904469]
  [0.99438934 1.23491975 1.49268019]
  [0.47118641 1.38838561 0.95740668]]

 [[1.59660853 0.84220878 1.34893072]
  [0.42058461 1.30950822 0.71190361]
  [1.18627053 1.08254639 1.32932835]
  [1.24032431 0.61237789 0.18698841]]

 [[1.2295566  1.69133624 0.4946793 ]
  [0.81134457 0.59124721 0.78486188]
  [1.13825046 0.51160713 1.09180498]
  [1.66942946 0.67838012 0.55958862]]

 [[1.34562397 1.39262527 0.66889749]
  [0.89243448 0.6526284  0.25878394]
  [1.04506148 0.75596063 0.70511219]
  [0.73239162 1.04618532 1.18145216]]

 [[1.56169564 0.62577836 1.10436556]
  [1.65223447 0.43820447 0.58547456]
  [1.56394267 1.5974405  1.00942294]
  [0.58618005 0.98802592 0.2971562 ]]]
<class 'numpy.ndarray'>
(5, 4, 3)


#### Problem3- Find if an given point is inside or outside the circle

First find the logic how to check the point comes inside or outside the circle
Lets Ciccle had radius r and center point is Cx abd Cy. and point is Px and Py
we can check the distnace between PxPy and CxCy and compare with radius r if distance between P and C is less than
r than it is inside else outside

In [22]:
# Now we need to find the code how can we enter the input value in python3
Cx,Cy,r = input("Enter Cx, Cy and r: ").split()
# or use below
#Cx,Cy,r = map(float,input("Enter Cx, Cy and r: ").split())
print(Cx,Cy,r)

Enter Cx, Cy and r: 4 5 6
4 5 6


In [23]:
print(Cx,Cy,r)
print(type(Cx))
print(type(Cy))
print(type(r))

4 5 6
<class 'str'>
<class 'str'>
<class 'str'>


In [24]:
# Now input value of that point P (Px,Py)
Px,Py = input("Enter Input Px,Py : ").split()
# or use below
# Px,Py = map(float,input("Enter Input Px,Py : ").split())

Enter Input Px,Py : 5 6


In [26]:
print(Px,Py)
print(type(Px))
print(type(Py))

5 6
<class 'str'>
<class 'str'>


In [27]:
# check P(Px,Py) lies in C
d = (Cx-Px)**2 + (Cy-Py)**2 

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [28]:
# we can see all the input value are in string and we cannot perform mathematical operation on string so
# we have to convert them either integar or float
Cx = float(Cx)
print(Cx)
print(type(Cx))

Cy = float(Cy)
r = float(r)
Px = float(Px)
Py = float(Py)

4.0
<class 'float'>


In [29]:
import math

In [30]:
d = math.sqrt((Cx-Px)**2 + (Cy-Py)**2)
print(d)
print(type(d))

1.4142135623730951
<class 'float'>


In [31]:
if d > r:
    print("P lies outside the circle")
else:
    print("P lies inside the circle")

P lies inside the circle


#### Problem4- Find if an given point is inside or outside the rectangle

We need to find the logic first.
As we know rectangle has the 4 lines and If we think lets it is available in XY 2D graph and then If we have 
Top left coordinate is (Rx1,Ry1) and bottom right coordinate is (Rx2,Ry2). let say point has coordinate (Px3,Py3).
If Px lies inside the circle then It should be Rx1 < Px3 < Rx2 . If Py lies inside the circle then Ry1 > Py3 > Ry2
So now we can say that P will be lied inside the rectangle if Rx1<Px3<Rx2 & Ry1>Py3>Ry2
Now we have our logic ready so we need to convert our logic in code

In [1]:
###### input value for Rx1,Rx2 and Ry1,Ry2
Rx1,Ry1,Rx2,Ry2 = map(float,input("Input the Rectangle Topright and bottom left value Rx1 Ry1 Rx2 Ry2 : ").split())

Input the Rectangle Topright and bottom left value Rx1 Ry1 Rx2 Ry2 : 1 2 3 4


In [2]:
#####input value for Px3 Py3
Px3,Py3 = map(float, input("Input value of point Px3 Py3 : ").split())

Input value of point Px3 Py3 : 3 4


In [3]:
# now we will use our logic to check the P value lie inside or not
if Ry1 > Py3 > Ry2 and Rx1 < Px3 < Rx2:
    print("Point P lie inside the rectangle")
else:
    print("Point P does not lie inside the rectangle")

Point P does not lie inside the rectangle


####  Numpy ndarray manupulation

Most the common errors we get during below tasks
1. reshape
2. hstack
3. vstack

In [4]:
# let create a 5x4 random ndarray matrix
import numpy as np
A = np.random.rand(5,4)

In [5]:
print(A)
print(type(A))
print(A.shape)

[[0.83530511 0.295306   0.70936798 0.47022297]
 [0.69363216 0.33294733 0.50263619 0.16552641]
 [0.76239466 0.71349677 0.23553493 0.51674333]
 [0.40097746 0.06651848 0.10138855 0.49088978]
 [0.74274574 0.05390777 0.60049726 0.27948716]]
<class 'numpy.ndarray'>
(5, 4)


In [6]:
# reshape this matrix into vector row major order-- vector means 1 row n columns and this is row vector
# column vector like 1 column and n row
B = A.reshape(20,order = 'F')
print(B)

[0.83530511 0.69363216 0.76239466 0.40097746 0.74274574 0.295306
 0.33294733 0.71349677 0.06651848 0.05390777 0.70936798 0.50263619
 0.23553493 0.10138855 0.60049726 0.47022297 0.16552641 0.51674333
 0.49088978 0.27948716]


In [7]:
print(type(B))
print(B.shape)

<class 'numpy.ndarray'>
(20,)


In [8]:
C = np.reshape(A,20,order = 'F')
print(C)
print(type(C))
print(C.shape)

[0.83530511 0.69363216 0.76239466 0.40097746 0.74274574 0.295306
 0.33294733 0.71349677 0.06651848 0.05390777 0.70936798 0.50263619
 0.23553493 0.10138855 0.60049726 0.47022297 0.16552641 0.51674333
 0.49088978 0.27948716]
<class 'numpy.ndarray'>
(20,)


In [9]:
D = np.reshape(A,(20,1), order='F') ### column vector
print(D)
print(type(D))
print(D.shape)

[[0.83530511]
 [0.69363216]
 [0.76239466]
 [0.40097746]
 [0.74274574]
 [0.295306  ]
 [0.33294733]
 [0.71349677]
 [0.06651848]
 [0.05390777]
 [0.70936798]
 [0.50263619]
 [0.23553493]
 [0.10138855]
 [0.60049726]
 [0.47022297]
 [0.16552641]
 [0.51674333]
 [0.49088978]
 [0.27948716]]
<class 'numpy.ndarray'>
(20, 1)


In [10]:
E = np.reshape(A,(2,-1),order = 'F')  
## if we use -1 then -1 value will be replaced with value which will be same as like 
## A has shape 4x4 == 16total and rehsape we use 2,-1 then -1 will be lets x ( x * 2 =16, then x = 8  )
print(E)
print(type(E))
print(E.shape)

[[0.83530511 0.76239466 0.74274574 0.33294733 0.06651848 0.70936798
  0.23553493 0.60049726 0.16552641 0.49088978]
 [0.69363216 0.40097746 0.295306   0.71349677 0.05390777 0.50263619
  0.10138855 0.47022297 0.51674333 0.27948716]]
<class 'numpy.ndarray'>
(2, 10)


In [11]:
F = np.reshape(A,(2,-1),order = 'C')  
## if we use -1 then -1 value will be replaced with value which will be same as like 
## A has shape 4x4 == 16total and rehsape we use 2,-1 then -1 will be lets x ( x * 2 =16, then x = 8  )
print(F)
print(type(F))
print(F.shape)

[[0.83530511 0.295306   0.70936798 0.47022297 0.69363216 0.33294733
  0.50263619 0.16552641 0.76239466 0.71349677]
 [0.23553493 0.51674333 0.40097746 0.06651848 0.10138855 0.49088978
  0.74274574 0.05390777 0.60049726 0.27948716]]
<class 'numpy.ndarray'>
(2, 10)


In [12]:
G = np.random.rand(3,4,2)
print(G)
print(G.shape)
print(type(G))

[[[0.87831797 0.55432363]
  [0.42745116 0.43395348]
  [0.8370183  0.18063568]
  [0.23160175 0.32095555]]

 [[0.7098268  0.13321112]
  [0.6556087  0.37569922]
  [0.90786224 0.87366325]
  [0.80349816 0.91923418]]

 [[0.68685461 0.33068304]
  [0.91053173 0.48999916]
  [0.38934101 0.73500923]
  [0.19742301 0.209995  ]]]
(3, 4, 2)
<class 'numpy.ndarray'>


In [13]:
H = np.reshape(G,(12,2),order = "C")
print(H)
print(type(H))
print(H.shape)

[[0.87831797 0.55432363]
 [0.42745116 0.43395348]
 [0.8370183  0.18063568]
 [0.23160175 0.32095555]
 [0.7098268  0.13321112]
 [0.6556087  0.37569922]
 [0.90786224 0.87366325]
 [0.80349816 0.91923418]
 [0.68685461 0.33068304]
 [0.91053173 0.48999916]
 [0.38934101 0.73500923]
 [0.19742301 0.209995  ]]
<class 'numpy.ndarray'>
(12, 2)


### Stacking

In [14]:
# Lets create 2 random ndarray
A = np.random.rand(5,4)
print(A)

[[0.12459655 0.91409718 0.55360463 0.67110056]
 [0.07365894 0.45560919 0.50349155 0.46388016]
 [0.54338525 0.16707963 0.50537381 0.55811888]
 [0.24948347 0.25962368 0.29039427 0.29283507]
 [0.17454863 0.2711887  0.85824112 0.96447116]]


In [16]:
B = np.random.rand(5,2)
print(B)

[[0.32585651 0.75714856]
 [0.05953193 0.7465613 ]
 [0.00538318 0.72154423]
 [0.23075888 0.3222109 ]
 [0.09159711 0.19372137]]


In [18]:
AB = np.hstack((A,B)) ### stacking horozontally if you see row are same on both A and B
print(AB)
print(type(AB))
print(AB.shape)


[[0.12459655 0.91409718 0.55360463 0.67110056 0.32585651 0.75714856]
 [0.07365894 0.45560919 0.50349155 0.46388016 0.05953193 0.7465613 ]
 [0.54338525 0.16707963 0.50537381 0.55811888 0.00538318 0.72154423]
 [0.24948347 0.25962368 0.29039427 0.29283507 0.23075888 0.3222109 ]
 [0.17454863 0.2711887  0.85824112 0.96447116 0.09159711 0.19372137]]
<class 'numpy.ndarray'>
(5, 6)


In [19]:
BA = np.vstack((A,B)) ## we cannot vstack becuase total column are not same

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [20]:
C = np.random.rand(5,4)  ### total columns are same .. Vertically stacking
D = np.random.rand(3,4)
CD = np.vstack((C,D))
print(CD)
print(CD.shape)

[[0.18437299 0.85817799 0.96888313 0.71944057]
 [0.63660682 0.13629281 0.89092503 0.24898565]
 [0.6668177  0.51469552 0.6066066  0.2006204 ]
 [0.32699488 0.76695881 0.22716185 0.1778831 ]
 [0.54940513 0.75074074 0.17597109 0.24631769]
 [0.65944512 0.60018931 0.40570026 0.03102356]
 [0.51258787 0.49418395 0.32823831 0.84137496]
 [0.41032691 0.27401178 0.3324458  0.1773721 ]]
(8, 4)


In [1]:
import numpy as np

In [2]:
# Now we will see how we can do 3D (tensors) stacking
E = np.random.rand(5,4,3)
F = np.random.rand(5,2,3)
EF = np.hstack((E,F))
print(EF)
print(EF.shape)

[[[0.30004075 0.0023515  0.87075018]
  [0.07800703 0.16212401 0.32026226]
  [0.90878319 0.62638163 0.64216792]
  [0.52972859 0.24432604 0.72515382]
  [0.01556475 0.05791419 0.23752819]
  [0.64607228 0.79344656 0.45262142]]

 [[0.80579483 0.84375051 0.21461966]
  [0.37925888 0.33643549 0.13990556]
  [0.26973101 0.63587763 0.411129  ]
  [0.8993325  0.89613554 0.51360461]
  [0.46831577 0.10595789 0.06088683]
  [0.52260335 0.95513124 0.96089996]]

 [[0.75359071 0.96156712 0.16184309]
  [0.16176842 0.7321692  0.53769005]
  [0.06299379 0.34468488 0.35437394]
  [0.93680838 0.69595856 0.19328802]
  [0.38869081 0.72430942 0.2954752 ]
  [0.04949663 0.65589878 0.77155763]]

 [[0.64238647 0.47718491 0.35700987]
  [0.28741891 0.6023703  0.03615846]
  [0.25750329 0.01717494 0.76708871]
  [0.346028   0.00306327 0.80288623]
  [0.18854845 0.22739634 0.83971111]
  [0.14009337 0.36098582 0.99720911]]

 [[0.14576949 0.01913776 0.67776653]
  [0.0346728  0.60573812 0.78649857]
  [0.01107887 0.14625836 0.544

In [5]:
# for vstack column and width should be same
G = np.random.rand(3,4,3)
H = np.random.rand(2,4,2)
GH = np.vstack((G,H))
print(GH)
print(GH.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 3 and the array at index 1 has size 2

In [7]:
# for vstack column and width should be same
I = np.random.rand(3,4,2)
J = np.random.rand(2,4,2)
IJ = np.vstack((I,J))
print(IJ)
print(IJ.shape)

[[[0.65550855 0.58289666]
  [0.78002693 0.02947154]
  [0.10943494 0.42620084]
  [0.57943855 0.68420582]]

 [[0.9973478  0.66530823]
  [0.50182606 0.31627897]
  [0.40200032 0.72455601]
  [0.72901163 0.68359589]]

 [[0.47692423 0.10001541]
  [0.40650889 0.44551758]
  [0.50504602 0.51670698]
  [0.48328588 0.31466084]]

 [[0.52182872 0.78862102]
  [0.27186683 0.85012875]
  [0.69278132 0.42046396]
  [0.5617193  0.8699445 ]]

 [[0.48469143 0.93613286]
  [0.18180654 0.17079934]
  [0.21561994 0.31124333]
  [0.00422132 0.89809366]]]
(5, 4, 2)


In [8]:
# for vstack column and width should be same.. in all case width should be same with either Row or column
K = np.random.rand(3,4,2)
L = np.random.rand(3,4,1)
KL = np.hstack((K,L))
print(KL)
print(KL.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 2 and the array at index 1 has size 1

In [9]:
# for vstack column and width should be same.. in all case width should be same with either Row or column
K = np.random.rand(3,4,2)
L = np.random.rand(3,4,1)
KL = np.vstack((K,L))
print(KL)
print(KL.shape)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 2 and the array at index 1 has size 1